### ISSUE TITLE
Maven can't resolve some dependencies

### ISSUE THREAD

**Issue by donhuvy** [IanDarwin/darwinsys-api#1]
Dear author, I have a problem with maven dependencies resolving:

https://github.com/IanDarwin/darwinsys-api/blob/master/pom.xml#L117
https://github.com/IanDarwin/darwinsys-api/blob/master/pom.xml#L130
https://github.com/IanDarwin/darwinsys-api/blob/master/pom.xml#L143

I have tried change version, but not succesful. This is screenshot:

![bug](https://cloud.githubusercontent.com/assets/1328316/6090782/599aff40-aeb9-11e4-9dd7-6c12eeab9de8.PNG)

**Comment by IanDarwin** [comment]
On 2015-02-06 23:06, donhuvy wrote:
>
> Dear author, I have a problem with maven dependencies resolving:
>
> https://github.com/IanDarwin/darwinsys-api/blob/master/pom.xml#L117
> https://github.com/IanDarwin/darwinsys-api/blob/master/pom.xml#L130
> https://github.com/IanDarwin/darwinsys-api/blob/master/pom.xml#L143
>
> I have tried change version, but not succesful. This is screenshot:
>
>
Hi, and thanks for your interest in my software!

However, your screenshot isn't useful. I need a typescript session of 
running Maven that shows what it did and what actually fails. Please 
review http://darwinsys.com/reporting.html and try again.

Thanks

**Comment by donhuvy** [comment]
I am sorry, I have been deleted the above project. ( I used https://github.com/IanDarwin/darwinsys-api/blob/master/pom.xml ). However, I import dependencies manually, and no problem.

**Comment by IanDarwin** [comment]
Problem no longer observed, closing the issue
